---
- name: install multiple s/w packages
  hosts: all
  tasks:
   - name: implementing loops
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree, b: present, c: yes}
      - {a: git, b: present, c: yes}
      - {a: apache2, b: absent, c: no}
      - {a: maven, b: present, c: yes}
...
       
