---
- name: configuring tomcat8
  hosts: all
  tasks:
   - name: Install tomcat8
     apt:
      name: tomcat8
      state: present
   - name: copy the tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8
   - name: change the port of tomcat8 from 8080 to 7000
     replace:
      regexp: 8080
      replace: 7000
      path: /etc/tomcat8/server.xml
   - name: restart
     service:
      name: tomcat8
      state: restarted
   - name: check url response of server1
     uri:
      url: http://172.16.3.182
      status_code: 200
   - name: check url response of server2
     uri:
      url: http://172.16.3.46
      status_code: 200
...


